//----------------------
// <auto-generated>
//     Generated using the NJsonSchema v10.2.2.0 (Newtonsoft.Json v9.0.0.0) (http://NJsonSchema.org)
// </auto-generated>
//----------------------

namespace OCPP.Generated
{
    #pragma warning disable // Disable all warnings

    /// <summary>This class does not get 'AdditionalProperties = false' in the schema generation, so it can be extended with arbitrary JSON properties to allow adding custom data.</summary>
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "10.2.2.0 (Newtonsoft.Json v9.0.0.0)")]
    public partial class CustomDataType 
    {
        [Newtonsoft.Json.JsonProperty("vendorId", Required = Newtonsoft.Json.Required.Always)]
        public string VendorId { get; set; }
    
        private System.Collections.Generic.IDictionary<string, object> _additionalProperties = new System.Collections.Generic.Dictionary<string, object>();
    
        [Newtonsoft.Json.JsonExtensionData]
        public System.Collections.Generic.IDictionary<string, object> AdditionalProperties
        {
            get { return _additionalProperties; }
            set { _additionalProperties = value; }
        }
    
    
    }
    
    /// <summary>This contains the progress status of the firmware installation.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "10.2.2.0 (Newtonsoft.Json v9.0.0.0)")]
    public enum FirmwareStatusEnumType
    {
        [System.Runtime.Serialization.EnumMember(Value = @"Downloaded")]
        Downloaded = 0,
    
        [System.Runtime.Serialization.EnumMember(Value = @"DownloadFailed")]
        DownloadFailed = 1,
    
        [System.Runtime.Serialization.EnumMember(Value = @"Downloading")]
        Downloading = 2,
    
        [System.Runtime.Serialization.EnumMember(Value = @"DownloadScheduled")]
        DownloadScheduled = 3,
    
        [System.Runtime.Serialization.EnumMember(Value = @"DownloadPaused")]
        DownloadPaused = 4,
    
        [System.Runtime.Serialization.EnumMember(Value = @"Idle")]
        Idle = 5,
    
        [System.Runtime.Serialization.EnumMember(Value = @"InstallationFailed")]
        InstallationFailed = 6,
    
        [System.Runtime.Serialization.EnumMember(Value = @"Installing")]
        Installing = 7,
    
        [System.Runtime.Serialization.EnumMember(Value = @"Installed")]
        Installed = 8,
    
        [System.Runtime.Serialization.EnumMember(Value = @"InstallRebooting")]
        InstallRebooting = 9,
    
        [System.Runtime.Serialization.EnumMember(Value = @"InstallScheduled")]
        InstallScheduled = 10,
    
        [System.Runtime.Serialization.EnumMember(Value = @"InstallVerificationFailed")]
        InstallVerificationFailed = 11,
    
        [System.Runtime.Serialization.EnumMember(Value = @"InvalidSignature")]
        InvalidSignature = 12,
    
        [System.Runtime.Serialization.EnumMember(Value = @"SignatureVerified")]
        SignatureVerified = 13,
    
    }
    
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "10.2.2.0 (Newtonsoft.Json v9.0.0.0)")]
    public partial class Anonymous 
    {
        [Newtonsoft.Json.JsonProperty("customData", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public CustomDataType CustomData { get; set; }
    
        [Newtonsoft.Json.JsonProperty("status", Required = Newtonsoft.Json.Required.Always)]
        [Newtonsoft.Json.JsonConverter(typeof(Newtonsoft.Json.Converters.StringEnumConverter))]
        public FirmwareStatusEnumType Status { get; set; }
    
        /// <summary>The request id that was provided in the
        /// UpdateFirmwareRequest that started this firmware update.
        /// This field is mandatory, unless the message was triggered by a TriggerMessageRequest AND there is no firmware update ongoing.
        /// </summary>
        [Newtonsoft.Json.JsonProperty("requestId", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public int RequestId { get; set; }
    
    
    }
}