//----------------------
// <auto-generated>
//     Generated using the NJsonSchema v10.2.2.0 (Newtonsoft.Json v9.0.0.0) (http://NJsonSchema.org)
// </auto-generated>
//----------------------

namespace OCPP.Generated
{
    #pragma warning disable // Disable all warnings

    /// <summary>This class does not get 'AdditionalProperties = false' in the schema generation, so it can be extended with arbitrary JSON properties to allow adding custom data.</summary>
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "10.2.2.0 (Newtonsoft.Json v9.0.0.0)")]
    public partial class CustomDataType 
    {
        [Newtonsoft.Json.JsonProperty("vendorId", Required = Newtonsoft.Json.Required.Always)]
        public string VendorId { get; set; }
    
        private System.Collections.Generic.IDictionary<string, object> _additionalProperties = new System.Collections.Generic.Dictionary<string, object>();
    
        [Newtonsoft.Json.JsonExtensionData]
        public System.Collections.Generic.IDictionary<string, object> AdditionalProperties
        {
            get { return _additionalProperties; }
            set { _additionalProperties = value; }
        }
    
    
    }
    
    /// <summary>This contains the status of the log upload.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "10.2.2.0 (Newtonsoft.Json v9.0.0.0)")]
    public enum UploadLogStatusEnumType
    {
        [System.Runtime.Serialization.EnumMember(Value = @"BadMessage")]
        BadMessage = 0,
    
        [System.Runtime.Serialization.EnumMember(Value = @"Idle")]
        Idle = 1,
    
        [System.Runtime.Serialization.EnumMember(Value = @"NotSupportedOperation")]
        NotSupportedOperation = 2,
    
        [System.Runtime.Serialization.EnumMember(Value = @"PermissionDenied")]
        PermissionDenied = 3,
    
        [System.Runtime.Serialization.EnumMember(Value = @"Uploaded")]
        Uploaded = 4,
    
        [System.Runtime.Serialization.EnumMember(Value = @"UploadFailure")]
        UploadFailure = 5,
    
        [System.Runtime.Serialization.EnumMember(Value = @"Uploading")]
        Uploading = 6,
    
        [System.Runtime.Serialization.EnumMember(Value = @"AcceptedCanceled")]
        AcceptedCanceled = 7,
    
    }
    
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "10.2.2.0 (Newtonsoft.Json v9.0.0.0)")]
    public partial class Anonymous 
    {
        [Newtonsoft.Json.JsonProperty("customData", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public CustomDataType CustomData { get; set; }
    
        [Newtonsoft.Json.JsonProperty("status", Required = Newtonsoft.Json.Required.Always)]
        [Newtonsoft.Json.JsonConverter(typeof(Newtonsoft.Json.Converters.StringEnumConverter))]
        public UploadLogStatusEnumType Status { get; set; }
    
        /// <summary>The request id that was provided in GetLogRequest that started this log upload. This field is mandatory,
        /// unless the message was triggered by a TriggerMessageRequest AND there is no log upload ongoing.
        /// </summary>
        [Newtonsoft.Json.JsonProperty("requestId", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public int RequestId { get; set; }
    
    
    }
}